version: '3.1'

services:
  tennis-service:
    image: richrocksmy/tennis-service:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
        - "5432:5432"